"""add mcp connections

Revision ID: 4dcaf666b40e
Revises: 6a1f4c8d0b57
Create Date: 2026-08-03 15:44:21.576335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcaf666b40e'
down_revision: Union[str, Sequence[str], None] = '6a1f4c8d0b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate also proposed dropping the hand-written HNSW/GIN indexes on document_chunks
    # (they aren't declared in the SQLAlchemy models) — removed from this migration; only the
    # mcp_connections table is a real, intentional change.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_url', sa.String(), nullable=False),
    sa.Column('auth_type', sa.Enum('api_token', 'oauth2', name='mcp_auth_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connected', 'token_expired', 'error', name='mcp_connection_status'), server_default='pending', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('encrypted_api_token', sa.Text(), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_client_id', sa.String(), nullable=True),
    sa.Column('encrypted_oauth_client_secret', sa.Text(), nullable=True),
    sa.Column('oauth_token_endpoint', sa.String(), nullable=True),
    sa.Column('oauth_state', sa.String(), nullable=True),
    sa.Column('oauth_pkce_verifier', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_state')
    )
    op.create_index(op.f('ix_mcp_connections_created_by'), 'mcp_connections', ['created_by'], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security (hand-written) ---
    # Shared across all users (like source_documents), not owner-scoped like chat tables.
    # Backend writes go through the service-role key (bypasses RLS) via app/database/mcp_connections.py.
    op.execute("ALTER TABLE mcp_connections ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY mcp_connections_authenticated_read ON mcp_connections "
        "FOR SELECT USING (auth.role() = 'authenticated')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # RLS policy is dropped implicitly by DROP TABLE below.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_connections_created_by'), table_name='mcp_connections')
    op.drop_table('mcp_connections')
    # ### end Alembic commands ###

    sa.Enum(name='mcp_connection_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='mcp_auth_type').drop(op.get_bind(), checkfirst=True)
